const applicationWorth = {
  enrichment: 0.5,
  farmingForDummies: 0.5,
  gemstonePowerScroll: 0.5,
  woodSingularity: 0.5,
  artOfWar: 0.6,
  fumingPotatoBook: 0.6,
  gemstoneSlots: 0.6,
  runes: 0.6,
  tunedTransmission: 0.7,
  pocketSackInASack: 0.7,
  essence: 0.75,
  goldenBounty: 0.75,
  silex: 0.75,
  artOfPeace: 0.8,
  divanPowderCoating: 0.8,
  pesthuntingGuide: 0.8,
  jalapenoBook: 0.8,
  manaDisintegrator: 0.8,
  recomb: 0.8,
  thunderInABottle: 0.8,
  enchants: 0.85,
  shensAuctionPrice: 0.85,
  dye: 0.9,
  gemstoneChambers: 0.9,
  attributes: 1,
  drillPart: 1,
  etherwarp: 1,
  masterStar: 1,
  gemstone: 1,
  hotPotatoBook: 1,
  necronBladeScroll: 1,
  polarvoid: 1,
  prestigeItem: 1,
  reforge: 1,
  winningBid: 1,

  petCandy: 0.65,
  soulboundPetSkins: 0.8,
  petItem: 1,
};

const enchantsWorth = {
  counter_strike: 0.2,
  big_brain: 0.35,
  ultimate_inferno: 0.35,
  overload: 0.35,
  ultimate_soul_eater: 0.35,
  ultimate_fatal_tempo: 0.65,
};

module.exports = {
  applicationWorth,
  enchantsWorth,
};
