const reforges = {
  // Low Reforge Stones
  stiff: 'hardened_wood',
  salty: 'salt_cube',
  aote_stone: 'aote_stone',
  waxed: 'blaze_wax',
  rooted: 'burrowing_spores',
  candied: 'candy_corn',
  perfect: 'diamond_atom',
  fleet: 'diamonite',
  fabled: 'dragon_claw',
  spiked: 'dragon_scale',
  hyper: 'endstone_geode',
  coldfused: 'entropy_suppressor',
  blooming: 'flowering_bouquet',
  jaded: 'jaderald',
  jerry: 'jerry_stone',
  magnetic: 'lapis_crystal',
  earthy: 'large_walnut',
  fortified: 'meteor_shard',
  gilded: 'midas_jewel',
  cubic: 'molten_cube',
  necrotic: 'necromancer_brooch',
  fruitful: 'onyx',
  precise: 'optical_lens',
  mossy: 'overgrown_grass',
  pitchin: 'pitchin_koi',
  undead: 'premium_flesh',
  mithraic: 'pure_mithril',
  reinforced: 'rare_diamond',
  ridiculous: 'red_nose',
  loving: 'red_scarf',
  auspicious: 'rock_gemstone',
  treacherous: 'rusty_anchor',
  headstrong: 'salmon_opal',
  strengthened: 'searing_stone',
  glistening: 'shiny_prism',
  bustling: 'skymart_brochure',
  spiritual: 'spirit_decoy',
  suspicious: 'suspicious_vial',

  // High Reforge Stones
  ambered: 'amber_material',
  blessed: 'blessed_fruit',
  bulky: 'bulky_stone',
  submerged: 'deep_sea_orb',
  renowned: 'dragon_horn',
  giant: 'giant_tooth',
  bountiful: 'golden_ball',
  chomp: 'kuudra_mandible',
  lucky: 'lucky_dice',
  stellar: 'petrified_starfall',
  ancient: 'precursor_gear',
  refined: 'refined_amber',
  empowered: 'sadans_brooch',
  withered: 'wither_blood',
  heated: 'hot_stuff',

  // Non-bazaar
  dirty: 'dirt_bottle',
  moil: 'moil_log',
  toil: 'toil_log',
};

module.exports = {
  reforges,
};
