const reforges = {
  perfect: 'diamond_atom',
  spiked: 'dragon_scale',
  fabled: 'dragon_claw',
  renowned: 'dragon_horn',
  cubic: 'molten_cube',
  reinforced: 'rare_diamond',
  magnetic: 'lapis_crystal',
  gilded: 'midas_jewel',
  fruitful: 'onyx',
  precise: 'optical_lens',
  ridiculous: 'red_nose',
  loving: 'red_scarf',
  spiritual: 'spirit_stone',
  warped: 'warped_stone',
  giant: 'giant_tooth',
  empowered: 'sadans_brooch',
  moil: 'moil_log',
  dirty: 'dirt_bottle',
  toil: 'toil_log',
  refined: 'refined_amber',
  blessed: 'blessed_fruit',
  candied: 'candy_corn',
  submerged: 'deep_sea_orb',
  ancient: 'precursor_gear',
  withered: 'wither_blood',
  aote_stone: 'aote_stone',
  ambered: 'amber_material',
  jaded: 'jaderald',
  auspicious: 'rock_gemstone',
  fleet: 'diamonite',
  waxed: 'blaze_wax',
  strengthened: 'searing_stone',
  glistening: 'shiny_prism',
  chomp: 'kuudra_mandible',
  fortified: 'meteor_shard',
  undead: 'premium_flesh',
  necrotic: 'necromancer_brooch',
  suspicious: 'suspicious_vial',
  headstrong: 'salmon_opal',
  mithraic: 'pure_mithril',
  stellar: 'petrified_starfall',
  bountiful: 'golden_ball',
  heated: 'hot_stuff',
  coldfused: 'entropy_suppressor',
  pitchin: 'pitchin_koi',
};

module.exports = {
  reforges,
};
