const reforges = {
    // Low Reforge Stones
    stiff: 'HARDENED_WOOD',
    salty: 'SALT_CUBE',
    aote_stone: 'AOTE_STONE',
    waxed: 'BLAZE_WAX',
    rooted: 'BURROWING_SPORES',
    candied: 'CANDY_CORN',
    perfect: 'DIAMOND_ATOM',
    fleet: 'DIAMONITE',
    fabled: 'DRAGON_CLAW',
    spiked: 'DRAGON_SCALE',
    hyper: 'ENDSTONE_GEODE',
    coldfusion: 'ENTROPY_SUPPRESSOR',
    blooming: 'FLOWERING_BOUQUET',
    jaded: 'JADERALD',
    jerry: 'JERRY_STONE',
    magnetic: 'LAPIS_CRYSTAL',
    earthy: 'LARGE_WALNUT',
    fortified: 'METEOR_SHARD',
    gilded: 'MIDAS_JEWEL',
    cubic: 'MOLTEN_CUBE',
    necrotic: 'NECROMANCER_BROOCH',
    fruitful: 'ONYX',
    precise: 'OPTICAL_LENS',
    mossy: 'OVERGROWN_GRASS',
    pitchin: 'PITCHIN_KOI',
    undead: 'PREMIUM_FLESH',
    mithraic: 'PURE_MITHRIL',
    reinforced: 'RARE_DIAMOND',
    ridiculous: 'RED_NOSE',
    loving: 'RED_SCARF',
    auspicious: 'ROCK_GEMSTONE',
    treacherous: 'RUSTY_ANCHOR',
    headstrong: 'SALMON_OPAL',
    strengthened: 'SEARING_STONE',
    glistening: 'SHINY_PRISM',
    bustling: 'SKYMART_BROCHURE',
    spiritual: 'SPIRIT_DECOY',
    suspicious: 'SUSPICIOUS_VIAL',
    fanged: 'FULL_JAW_FANGED_KIT',
    blood_soaked: 'PRESUMED_GALLON_OF_RED_PAINT',
    snowy: 'TERRY_SNOWGLOBE',

    // High Reforge Stones
    ambered: 'AMBER_MATERIAL',
    blessed: 'BLESSED_FRUIT',
    bulky: 'BULKY_STONE',
    submerged: 'DEEP_SEA_ORB',
    renowned: 'DRAGON_HORN',
    giant: 'GIANT_TOOTH',
    bountiful: 'GOLDEN_BALL',
    chomp: 'KUUDRA_MANDIBLE',
    lucky: 'LUCKY_DICE',
    stellar: 'PETRIFIED_STARFALL',
    ancient: 'PRECURSOR_GEAR',
    refined: 'REFINED_AMBER',
    empowered: 'SADAN_BROOCH',
    withered: 'WITHER_BLOOD',
    heated: 'HOT_STUFF',
    festive: 'FROZEN_BAUBLE',

    // Non-bazaar
    dirty: 'DIRT_BOTTLE',
    moil: 'MOIL_LOG',
    toil: 'TOIL_LOG',
};

module.exports = {
    reforges,
};
